import { SoundscapeTrack } from '../../types';

export const TRACK_CATEGORIES = [
  'All',
  'Music & Flow',
  'Nature & Elements',
  'Binaural & Brainwaves',
  'Ambient & Noise',
] as const;

export const SOUNDSCAPE_TRACKS: SoundscapeTrack[] = [
  // --- ORIGINAL 6 TRACKS ---
  {
    id: 'lofi',
    title: 'Lo-Fi Chill Rhodes Chords',
    subtitle: 'Warm Electric Piano Harmonic Progression',
    category: 'Music & Flow',
    description: 'Generative four-chord jazz progression (Dm9 → G13 → Cmaj9 → Am7) with analog detune and soft low-pass filter.',
    bpm: 72,
  },
  {
    id: 'rain',
    title: 'Midnight Rain on Glass',
    subtitle: 'Filtered Rainstorm with Organic Droplets',
    category: 'Nature & Elements',
    description: 'Pink noise bed with randomized acoustic raindrop transients. Perfect for calming anxiety and masking harsh background noises.',
  },
  {
    id: 'brown-noise',
    title: 'Deep Warm Brown Noise',
    subtitle: 'Full-Spectrum Acoustic Isolation',
    category: 'Ambient & Noise',
    description: '1/f² power density curve low-passed at 450Hz. The gold standard for blocking out open-office conversations and HVAC hum.',
  },
  {
    id: 'gamma-40hz',
    title: '40Hz Gamma Binaural Beats',
    subtitle: 'Gamma Frequency Entrainment for Coding Flow',
    category: 'Binaural & Brainwaves',
    description: 'Stereo carrier frequencies (200Hz Left / 240Hz Right) inducing a 40Hz gamma rhythm associated with high cognitive focus.',
  },
  {
    id: 'cyberpunk',
    title: 'Cyberpunk Neon Arp',
    subtitle: '16th-Note Retro Synth Sequence',
    category: 'Music & Flow',
    description: 'Upbeat melodic sawtooth arpeggio in A minor. Keeps your typing tempo rhythmic during late-night debugging marathons.',
    bpm: 110,
  },
  {
    id: 'ambient-drone',
    title: 'Lush Space Ambient Drone',
    subtitle: 'Multi-Oscillator Sub-Bass Pad',
    category: 'Ambient & Noise',
    description: 'Harmonically rich continuous pad tuned in fifths and octaves. Ideal for architecture design and long-form code reviews.',
  },

  // --- 25 NEW TRACKS ---
  {
    id: 'lofi-beats',
    title: 'Lo-Fi Hip Hop Study Groove',
    subtitle: 'Mellow Beats with Warm Vinyl Flutter',
    category: 'Music & Flow',
    description: 'Soft sub kick drum, subtle brush snare on 2 and 4, and dusty analog vinyl crackle beneath warm Rhodes keys.',
    bpm: 67,
  },
  {
    id: 'synthwave-drive',
    title: 'Outrun Synthwave Night Drive',
    subtitle: '80s Driving Bassline & Neon Leads',
    category: 'Music & Flow',
    description: 'Rolling 16th-note analog bassline in F minor with filtered saw sweeps and nostalgic synthwave drive.',
    bpm: 107,
  },
  {
    id: 'piano-solitude',
    title: 'Minimalist Neo-Classical Piano',
    subtitle: 'Contemplative Felt Piano Arpeggios',
    category: 'Music & Flow',
    description: 'Delicate, slow piano notes resonating in a serene chamber. Perfect for deep concentration and bug fixing.',
    bpm: 65,
  },
  {
    id: 'chiptune-8bit',
    title: 'Arcade 8-Bit Nostalgia',
    subtitle: 'Retro Chiptune Gameboy Arpeggio',
    category: 'Music & Flow',
    description: 'Playful square-wave arpeggio reminiscent of 90s handheld consoles and classic pixel RPGs.',
    bpm: 125,
  },
  {
    id: 'jazz-cafe',
    title: 'Midnight Velvet Jazz Cafe',
    subtitle: 'Muted Major 7th Chords & Upright Bass',
    category: 'Music & Flow',
    description: 'Sophisticated modal jazz chord voicing (Ebmaj7, Cm7, Fm7) creating a warm late-night cafe sanctuary.',
    bpm: 70,
  },
  {
    id: 'coding-pulse',
    title: '128 BPM Techno Code Flow',
    subtitle: 'Minimal Sub Kick & Crisp Hi-Hats',
    category: 'Music & Flow',
    description: 'Steady 128 BPM electronic pulse designed to lock your cognitive state into rhythmic hyper-focus.',
    bpm: 128,
  },
  {
    id: 'thunderstorm',
    title: 'Heavy Thunderstorm & Downpour',
    subtitle: 'Rolling Low-Frequency Thunder Deluge',
    category: 'Nature & Elements',
    description: 'Soothing heavy rainfall coupled with distant rolling thunder booms that resonate deeply without startling.',
  },
  {
    id: 'forest-birds',
    title: 'Morning Forest Birds & Mist',
    subtitle: 'Canopy Breeze with Woodland Chirps',
    category: 'Nature & Elements',
    description: 'Refreshing pine forest wind breeze accompanied by melodic, randomized organic songbird chirps.',
  },
  {
    id: 'waterfall',
    title: 'Cascading Mountain Waterfall',
    subtitle: 'Broad-Spectrum Rushing Hydro Acoustics',
    category: 'Nature & Elements',
    description: 'Powerful, continuous roar of clean alpine falling water. Unrivaled acoustic privacy and focus shield.',
  },
  {
    id: 'deep-ocean',
    title: 'Mariana Trench Deep Ocean',
    subtitle: 'Sub-Bass Tides & Submarine Sonar Ping',
    category: 'Nature & Elements',
    description: 'Slow sub-bass ocean swell with occasional tranquil submarine sonar pings echoing through the abyss.',
  },
  {
    id: 'fireplace',
    title: 'Cozy Winter Hearth Fireplace',
    subtitle: 'Crackling Embers & Warm Thermal Glow',
    category: 'Nature & Elements',
    description: 'Gentle wood pops, crackling ember transients, and warm thermal hum for a cozy programming evening.',
  },
  {
    id: 'wind-pines',
    title: 'Alpine Wind in the Pines',
    subtitle: 'Mountain Pass Whistling Breeze',
    category: 'Nature & Elements',
    description: 'Fluctuating wind gusts filtering through high-altitude evergreen needles, wiping away cognitive fatigue.',
  },
  {
    id: 'night-crickets',
    title: 'Starlight Summer Crickets',
    subtitle: 'Nocturnal Meadow Rhythmic Chorus',
    category: 'Nature & Elements',
    description: 'Delicate high-frequency crickets chirping rhythmically under a quiet starry midnight sky.',
  },
  {
    id: 'coffee-shop',
    title: 'Cozy Parisian Coffeehouse',
    subtitle: 'Soft Ambient Murmur & Ceramic Clinks',
    category: 'Nature & Elements',
    description: 'Gentle background coffee shop murmur with soft ceramic cup clinks, simulating a productive cafe corner.',
  },
  {
    id: 'alpha-waves',
    title: '10Hz Alpha Mindstate Entrainment',
    subtitle: 'Binaural Flow for Creative Problem Solving',
    category: 'Binaural & Brainwaves',
    description: 'Stereo carriers (210Hz / 220Hz) producing a gentle 10Hz alpha wave associated with relaxed mental alertness.',
  },
  {
    id: 'theta-deep',
    title: '6Hz Deep Theta Meditation',
    subtitle: 'Subconscious Insight & Introspection',
    category: 'Binaural & Brainwaves',
    description: '6Hz difference frequency (180Hz / 186Hz) promoting deeply relaxed, meditative states for complex logic design.',
  },
  {
    id: 'delta-sleep',
    title: '2Hz Delta Deep Restoration',
    subtitle: 'Ultra-Low Frequency Brainwave Sync',
    category: 'Binaural & Brainwaves',
    description: 'Ultra-deep 2Hz binaural entrainment for post-incident decompression, eye rest, or power nap recovery.',
  },
  {
    id: 'solfeggio-528',
    title: '528Hz Miracle Healing Frequency',
    subtitle: 'Pure Golden Ratio Harmonic Resonance',
    category: 'Binaural & Brainwaves',
    description: 'Pure 528Hz sine wave revered in acoustic geometry for clearing stress, mental clutter, and fatigue.',
  },
  {
    id: 'tibetan-bowls',
    title: 'Himalayan Singing Bowls',
    subtitle: 'Harmonic Brass Bowls with Acoustic Vibrato',
    category: 'Binaural & Brainwaves',
    description: 'Multiphonic harmonic resonance of antique meditation bowls vibrating in acoustic phase harmony.',
  },
  {
    id: 'zen-garden',
    title: 'Zen Temple Garden & Koto',
    subtitle: 'Japanese Hirajoshi Pentatonic Plucks',
    category: 'Binaural & Brainwaves',
    description: 'Tranquil koto string plucks arranged in traditional Japanese Hirajoshi harmony with windchimes.',
  },
  {
    id: 'white-noise',
    title: 'Crisp Uniform White Noise',
    subtitle: 'Total Spectrum Acoustic Blanket',
    category: 'Ambient & Noise',
    description: 'Equal power across all audible frequencies. Instantly conceals sudden office noises and telephone voices.',
  },
  {
    id: 'pink-noise',
    title: 'Balanced Natural Pink Noise',
    subtitle: '1/f Equal Energy Per Octave',
    category: 'Ambient & Noise',
    description: 'More natural and soothing than white noise with stronger low-end balance. Proven to enhance sleep and memory.',
  },
  {
    id: 'space-voyager',
    title: 'Interstellar Deep Space Voyager',
    subtitle: 'Cosmic Drone & Galaxy Soundscape',
    category: 'Ambient & Noise',
    description: 'Slow-evolving planetary sub-frequencies simulating the silent awe of drifting through deep cosmos.',
  },
  {
    id: 'ambient-pads',
    title: 'Ethereal Cloud Dreamscape Pads',
    subtitle: 'Lush Multi-Detuned Floating Chords',
    category: 'Ambient & Noise',
    description: 'Slow-drifting celestial synthesizer pads that float without sharp attacks, creating a timeless space.',
  },
  {
    id: 'cyber-matrix',
    title: 'Cyber Matrix Data Stream',
    subtitle: 'Dark Synth Drone with Telemetry Blips',
    category: 'Ambient & Noise',
    description: 'Futuristic sci-fi server room atmosphere with low reactor drone and microscopic data computation blips.',
  },
];
